/*
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ContinuousExportConfiguration
 */
public class ContinuousExportConfigurationTest {
    private final ContinuousExportConfiguration model = new ContinuousExportConfiguration();

    /**
     * Model tests for ContinuousExportConfiguration
     */
    @Test
    public void testContinuousExportConfiguration() {
        // TODO: test ContinuousExportConfiguration
    }

    /**
     * Test the property 'exportPath'
     */
    @Test
    public void exportPathTest() {
        // TODO: test exportPath
    }

    /**
     * Test the property 'exportStatusPath'
     */
    @Test
    public void exportStatusPathTest() {
        // TODO: test exportStatusPath
    }

    /**
     * Test the property 'lastKeysInPrefixRegexp'
     */
    @Test
    public void lastKeysInPrefixRegexpTest() {
        // TODO: test lastKeysInPrefixRegexp
    }

    /**
     * Test the property 'isContinuous'
     */
    @Test
    public void isContinuousTest() {
        // TODO: test isContinuous
    }

}
