/*
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RetentionPolicyWithCreationDateAllOf
 */
public class RetentionPolicyWithCreationDateAllOfTest {
    private final RetentionPolicyWithCreationDateAllOf model = new RetentionPolicyWithCreationDateAllOf();

    /**
     * Model tests for RetentionPolicyWithCreationDateAllOf
     */
    @Test
    public void testRetentionPolicyWithCreationDateAllOf() {
        // TODO: test RetentionPolicyWithCreationDateAllOf
    }

    /**
     * Test the property 'creationDate'
     */
    @Test
    public void creationDateTest() {
        // TODO: test creationDate
    }

}
