/*
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Config
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-09T13:58:34.593755+02:00[Asia/Jerusalem]")
public class Config {
  public static final String SERIALIZED_NAME_BLOCKSTORE_TYPE = "blockstore.type";
  @SerializedName(SERIALIZED_NAME_BLOCKSTORE_TYPE)
  private String blockstoreType;


  public Config blockstoreType(String blockstoreType) {
    
    this.blockstoreType = blockstoreType;
    return this;
  }

   /**
   * Get blockstoreType
   * @return blockstoreType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBlockstoreType() {
    return blockstoreType;
  }


  public void setBlockstoreType(String blockstoreType) {
    this.blockstoreType = blockstoreType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Config config = (Config) o;
    return Objects.equals(this.blockstoreType, config.blockstoreType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blockstoreType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Config {\n");
    sb.append("    blockstoreType: ").append(toIndentedString(blockstoreType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

