/*
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;

/**
 * ContinuousExportConfiguration
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-09T13:58:34.593755+02:00[Asia/Jerusalem]")
public class ContinuousExportConfiguration {
  public static final String SERIALIZED_NAME_EXPORT_PATH = "exportPath";
  @SerializedName(SERIALIZED_NAME_EXPORT_PATH)
  private URI exportPath;

  public static final String SERIALIZED_NAME_EXPORT_STATUS_PATH = "exportStatusPath";
  @SerializedName(SERIALIZED_NAME_EXPORT_STATUS_PATH)
  private URI exportStatusPath;

  public static final String SERIALIZED_NAME_LAST_KEYS_IN_PREFIX_REGEXP = "lastKeysInPrefixRegexp";
  @SerializedName(SERIALIZED_NAME_LAST_KEYS_IN_PREFIX_REGEXP)
  private List<String> lastKeysInPrefixRegexp = null;

  public static final String SERIALIZED_NAME_IS_CONTINUOUS = "isContinuous";
  @SerializedName(SERIALIZED_NAME_IS_CONTINUOUS)
  private Boolean isContinuous;


  public ContinuousExportConfiguration exportPath(URI exportPath) {
    
    this.exportPath = exportPath;
    return this;
  }

   /**
   * export objects to this path
   * @return exportPath
  **/
  @ApiModelProperty(example = "s3://company-bucket/path/to/export", required = true, value = "export objects to this path")

  public URI getExportPath() {
    return exportPath;
  }


  public void setExportPath(URI exportPath) {
    this.exportPath = exportPath;
  }


  public ContinuousExportConfiguration exportStatusPath(URI exportStatusPath) {
    
    this.exportStatusPath = exportStatusPath;
    return this;
  }

   /**
   * write export status object to this path
   * @return exportStatusPath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "s3://company-bucket/path/to/status", value = "write export status object to this path")

  public URI getExportStatusPath() {
    return exportStatusPath;
  }


  public void setExportStatusPath(URI exportStatusPath) {
    this.exportStatusPath = exportStatusPath;
  }


  public ContinuousExportConfiguration lastKeysInPrefixRegexp(List<String> lastKeysInPrefixRegexp) {
    
    this.lastKeysInPrefixRegexp = lastKeysInPrefixRegexp;
    return this;
  }

  public ContinuousExportConfiguration addLastKeysInPrefixRegexpItem(String lastKeysInPrefixRegexpItem) {
    if (this.lastKeysInPrefixRegexp == null) {
      this.lastKeysInPrefixRegexp = new ArrayList<String>();
    }
    this.lastKeysInPrefixRegexp.add(lastKeysInPrefixRegexpItem);
    return this;
  }

   /**
   * list of regexps of keys to exported last in each prefix (for signalling)
   * @return lastKeysInPrefixRegexp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[^SUCCESS$, .*_/_SUCCESS$]", value = "list of regexps of keys to exported last in each prefix (for signalling)")

  public List<String> getLastKeysInPrefixRegexp() {
    return lastKeysInPrefixRegexp;
  }


  public void setLastKeysInPrefixRegexp(List<String> lastKeysInPrefixRegexp) {
    this.lastKeysInPrefixRegexp = lastKeysInPrefixRegexp;
  }


  public ContinuousExportConfiguration isContinuous(Boolean isContinuous) {
    
    this.isContinuous = isContinuous;
    return this;
  }

   /**
   * if true, export every commit or merge to branch
   * @return isContinuous
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "if true, export every commit or merge to branch")

  public Boolean getIsContinuous() {
    return isContinuous;
  }


  public void setIsContinuous(Boolean isContinuous) {
    this.isContinuous = isContinuous;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContinuousExportConfiguration continuousExportConfiguration = (ContinuousExportConfiguration) o;
    return Objects.equals(this.exportPath, continuousExportConfiguration.exportPath) &&
        Objects.equals(this.exportStatusPath, continuousExportConfiguration.exportStatusPath) &&
        Objects.equals(this.lastKeysInPrefixRegexp, continuousExportConfiguration.lastKeysInPrefixRegexp) &&
        Objects.equals(this.isContinuous, continuousExportConfiguration.isContinuous);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exportPath, exportStatusPath, lastKeysInPrefixRegexp, isContinuous);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContinuousExportConfiguration {\n");
    sb.append("    exportPath: ").append(toIndentedString(exportPath)).append("\n");
    sb.append("    exportStatusPath: ").append(toIndentedString(exportStatusPath)).append("\n");
    sb.append("    lastKeysInPrefixRegexp: ").append(toIndentedString(lastKeysInPrefixRegexp)).append("\n");
    sb.append("    isContinuous: ").append(toIndentedString(isContinuous)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

