/*
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CredentialsWithSecret
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-09T13:58:34.593755+02:00[Asia/Jerusalem]")
public class CredentialsWithSecret {
  public static final String SERIALIZED_NAME_ACCESS_KEY_ID = "access_key_id";
  @SerializedName(SERIALIZED_NAME_ACCESS_KEY_ID)
  private String accessKeyId;

  public static final String SERIALIZED_NAME_ACCESS_SECRET_KEY = "access_secret_key";
  @SerializedName(SERIALIZED_NAME_ACCESS_SECRET_KEY)
  private String accessSecretKey;

  public static final String SERIALIZED_NAME_CREATION_DATE = "creation_date";
  @SerializedName(SERIALIZED_NAME_CREATION_DATE)
  private Long creationDate;


  public CredentialsWithSecret accessKeyId(String accessKeyId) {
    
    this.accessKeyId = accessKeyId;
    return this;
  }

   /**
   * Get accessKeyId
   * @return accessKeyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAccessKeyId() {
    return accessKeyId;
  }


  public void setAccessKeyId(String accessKeyId) {
    this.accessKeyId = accessKeyId;
  }


  public CredentialsWithSecret accessSecretKey(String accessSecretKey) {
    
    this.accessSecretKey = accessSecretKey;
    return this;
  }

   /**
   * Get accessSecretKey
   * @return accessSecretKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAccessSecretKey() {
    return accessSecretKey;
  }


  public void setAccessSecretKey(String accessSecretKey) {
    this.accessSecretKey = accessSecretKey;
  }


  public CredentialsWithSecret creationDate(Long creationDate) {
    
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getCreationDate() {
    return creationDate;
  }


  public void setCreationDate(Long creationDate) {
    this.creationDate = creationDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CredentialsWithSecret credentialsWithSecret = (CredentialsWithSecret) o;
    return Objects.equals(this.accessKeyId, credentialsWithSecret.accessKeyId) &&
        Objects.equals(this.accessSecretKey, credentialsWithSecret.accessSecretKey) &&
        Objects.equals(this.creationDate, credentialsWithSecret.creationDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessKeyId, accessSecretKey, creationDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CredentialsWithSecret {\n");
    sb.append("    accessKeyId: ").append(toIndentedString(accessKeyId)).append("\n");
    sb.append("    accessSecretKey: ").append(toIndentedString(accessSecretKey)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

