/*
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.RetentionPolicy;
import org.openapitools.client.model.RetentionPolicyRule;
import org.openapitools.client.model.RetentionPolicyWithCreationDateAllOf;
import org.threeten.bp.OffsetDateTime;

/**
 * RetentionPolicyWithCreationDate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-09T13:58:34.593755+02:00[Asia/Jerusalem]")
public class RetentionPolicyWithCreationDate {
  public static final String SERIALIZED_NAME_RULES = "rules";
  @SerializedName(SERIALIZED_NAME_RULES)
  private List<RetentionPolicyRule> rules = new ArrayList<RetentionPolicyRule>();

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_CREATION_DATE = "creation_date";
  @SerializedName(SERIALIZED_NAME_CREATION_DATE)
  private OffsetDateTime creationDate;


  public RetentionPolicyWithCreationDate rules(List<RetentionPolicyRule> rules) {
    
    this.rules = rules;
    return this;
  }

  public RetentionPolicyWithCreationDate addRulesItem(RetentionPolicyRule rulesItem) {
    this.rules.add(rulesItem);
    return this;
  }

   /**
   * Get rules
   * @return rules
  **/
  @ApiModelProperty(required = true, value = "")

  public List<RetentionPolicyRule> getRules() {
    return rules;
  }


  public void setRules(List<RetentionPolicyRule> rules) {
    this.rules = rules;
  }


  public RetentionPolicyWithCreationDate description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public RetentionPolicyWithCreationDate creationDate(OffsetDateTime creationDate) {
    
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getCreationDate() {
    return creationDate;
  }


  public void setCreationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetentionPolicyWithCreationDate retentionPolicyWithCreationDate = (RetentionPolicyWithCreationDate) o;
    return Objects.equals(this.rules, retentionPolicyWithCreationDate.rules) &&
        Objects.equals(this.description, retentionPolicyWithCreationDate.description) &&
        Objects.equals(this.creationDate, retentionPolicyWithCreationDate.creationDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rules, description, creationDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetentionPolicyWithCreationDate {\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

