/*
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Credentials;
import org.openapitools.client.model.CredentialsWithSecret;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.Group;
import org.openapitools.client.model.GroupCreation;
import org.openapitools.client.model.InlineResponse200;
import org.openapitools.client.model.InlineResponse2001;
import org.openapitools.client.model.InlineResponse2002;
import org.openapitools.client.model.InlineResponse2003;
import org.openapitools.client.model.InlineResponse2004;
import org.openapitools.client.model.Policy;
import org.openapitools.client.model.User;
import org.openapitools.client.model.UserCreation;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthApi
 */
@Ignore
public class AuthApiTest {

    private final AuthApi api = new AuthApi();

    
    /**
     * add group membership
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addGroupMembershipTest() throws ApiException {
        String groupId = null;
        String userId = null;
        api.addGroupMembership(groupId, userId);

        // TODO: test validations
    }
    
    /**
     * attach policy to group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void attachPolicyToGroupTest() throws ApiException {
        String groupId = null;
        String policyId = null;
        api.attachPolicyToGroup(groupId, policyId);

        // TODO: test validations
    }
    
    /**
     * attach policy to user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void attachPolicyToUserTest() throws ApiException {
        String userId = null;
        String policyId = null;
        api.attachPolicyToUser(userId, policyId);

        // TODO: test validations
    }
    
    /**
     * create credentials
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createCredentialsTest() throws ApiException {
        String userId = null;
        CredentialsWithSecret response = api.createCredentials(userId);

        // TODO: test validations
    }
    
    /**
     * create group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createGroupTest() throws ApiException {
        GroupCreation group = null;
        Group response = api.createGroup(group);

        // TODO: test validations
    }
    
    /**
     * create policy
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createPolicyTest() throws ApiException {
        Policy policy = null;
        Policy response = api.createPolicy(policy);

        // TODO: test validations
    }
    
    /**
     * create user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createUserTest() throws ApiException {
        UserCreation user = null;
        User response = api.createUser(user);

        // TODO: test validations
    }
    
    /**
     * delete credentials
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCredentialsTest() throws ApiException {
        String userId = null;
        String accessKeyId = null;
        api.deleteCredentials(userId, accessKeyId);

        // TODO: test validations
    }
    
    /**
     * delete group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteGroupTest() throws ApiException {
        String groupId = null;
        api.deleteGroup(groupId);

        // TODO: test validations
    }
    
    /**
     * delete group membership
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteGroupMembershipTest() throws ApiException {
        String groupId = null;
        String userId = null;
        api.deleteGroupMembership(groupId, userId);

        // TODO: test validations
    }
    
    /**
     * delete policy
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deletePolicyTest() throws ApiException {
        String policyId = null;
        api.deletePolicy(policyId);

        // TODO: test validations
    }
    
    /**
     * delete user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteUserTest() throws ApiException {
        String userId = null;
        api.deleteUser(userId);

        // TODO: test validations
    }
    
    /**
     * detach policy from group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void detachPolicyFromGroupTest() throws ApiException {
        String groupId = null;
        String policyId = null;
        api.detachPolicyFromGroup(groupId, policyId);

        // TODO: test validations
    }
    
    /**
     * detach policy from user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void detachPolicyFromUserTest() throws ApiException {
        String userId = null;
        String policyId = null;
        api.detachPolicyFromUser(userId, policyId);

        // TODO: test validations
    }
    
    /**
     * get credentials
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCredentialsTest() throws ApiException {
        String userId = null;
        String accessKeyId = null;
        Credentials response = api.getCredentials(userId, accessKeyId);

        // TODO: test validations
    }
    
    /**
     * get current user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCurrentUserTest() throws ApiException {
        InlineResponse200 response = api.getCurrentUser();

        // TODO: test validations
    }
    
    /**
     * get group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGroupTest() throws ApiException {
        String groupId = null;
        Group response = api.getGroup(groupId);

        // TODO: test validations
    }
    
    /**
     * get policy
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPolicyTest() throws ApiException {
        String policyId = null;
        Policy response = api.getPolicy(policyId);

        // TODO: test validations
    }
    
    /**
     * get user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserTest() throws ApiException {
        String userId = null;
        User response = api.getUser(userId);

        // TODO: test validations
    }
    
    /**
     * list group members
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listGroupMembersTest() throws ApiException {
        String groupId = null;
        String after = null;
        Integer amount = null;
        InlineResponse2001 response = api.listGroupMembers(groupId, after, amount);

        // TODO: test validations
    }
    
    /**
     * list group policies
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listGroupPoliciesTest() throws ApiException {
        String groupId = null;
        String after = null;
        Integer amount = null;
        InlineResponse2003 response = api.listGroupPolicies(groupId, after, amount);

        // TODO: test validations
    }
    
    /**
     * list groups
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listGroupsTest() throws ApiException {
        String after = null;
        Integer amount = null;
        InlineResponse2002 response = api.listGroups(after, amount);

        // TODO: test validations
    }
    
    /**
     * list policies
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listPoliciesTest() throws ApiException {
        String after = null;
        Integer amount = null;
        InlineResponse2003 response = api.listPolicies(after, amount);

        // TODO: test validations
    }
    
    /**
     * list user credentials
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listUserCredentialsTest() throws ApiException {
        String userId = null;
        String after = null;
        Integer amount = null;
        InlineResponse2004 response = api.listUserCredentials(userId, after, amount);

        // TODO: test validations
    }
    
    /**
     * list user groups
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listUserGroupsTest() throws ApiException {
        String userId = null;
        String after = null;
        Integer amount = null;
        InlineResponse2002 response = api.listUserGroups(userId, after, amount);

        // TODO: test validations
    }
    
    /**
     * list user policies
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listUserPoliciesTest() throws ApiException {
        String userId = null;
        String after = null;
        Integer amount = null;
        Boolean effective = null;
        InlineResponse2003 response = api.listUserPolicies(userId, after, amount, effective);

        // TODO: test validations
    }
    
    /**
     * list users
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listUsersTest() throws ApiException {
        String after = null;
        Integer amount = null;
        InlineResponse2001 response = api.listUsers(after, amount);

        // TODO: test validations
    }
    
    /**
     * update policy
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updatePolicyTest() throws ApiException {
        String policyId = null;
        Policy policy = null;
        Policy response = api.updatePolicy(policyId, policy);

        // TODO: test validations
    }
    
}
