/*
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Commit;
import org.openapitools.client.model.CommitCreation;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.InlineResponse2007;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CommitsApi
 */
@Ignore
public class CommitsApiTest {

    private final CommitsApi api = new CommitsApi();

    
    /**
     * create commit
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void commitTest() throws ApiException {
        String repository = null;
        String branch = null;
        CommitCreation commit = null;
        Commit response = api.commit(repository, branch, commit);

        // TODO: test validations
    }
    
    /**
     * get commit log for branch
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBranchCommitLogTest() throws ApiException {
        String repository = null;
        String branch = null;
        String after = null;
        Integer amount = null;
        InlineResponse2007 response = api.getBranchCommitLog(repository, branch, after, amount);

        // TODO: test validations
    }
    
    /**
     * get commit
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCommitTest() throws ApiException {
        String repository = null;
        String commitId = null;
        Commit response = api.getCommit(repository, commitId);

        // TODO: test validations
    }
    
}
