/*
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ContinuousExportConfiguration;
import org.openapitools.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExportApi
 */
@Ignore
public class ExportApiTest {

    private final ExportApi api = new ExportApi();

    
    /**
     * returns the current continuous export configuration of a branch
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getContinuousExportTest() throws ApiException {
        String repository = null;
        String branch = null;
        ContinuousExportConfiguration response = api.getContinuousExport(repository, branch);

        // TODO: test validations
    }
    
    /**
     * set continuous export state as repaired
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void repairTest() throws ApiException {
        String repository = null;
        String branch = null;
        api.repair(repository, branch);

        // TODO: test validations
    }
    
    /**
     * hook to be called in order to execute continuous export on branch
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void runTest() throws ApiException {
        String repository = null;
        String branch = null;
        String response = api.run(repository, branch);

        // TODO: test validations
    }
    
    /**
     * sets a new continuous export configuration of a branch
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setContinuousExportTest() throws ApiException {
        String repository = null;
        String branch = null;
        ContinuousExportConfiguration config = null;
        api.setContinuousExport(repository, branch, config);

        // TODO: test validations
    }
    
}
