/*
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MetadataApi
 */
@Ignore
public class MetadataApiTest {

    private final MetadataApi api = new MetadataApi();

    
    /**
     * creates symlink files corresponding to the given directory
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSymlinkTest() throws ApiException {
        String repository = null;
        String branch = null;
        String location = null;
        String response = api.createSymlink(repository, branch, location);

        // TODO: test validations
    }
    
}
