/*
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.InlineResponse2005;
import org.openapitools.client.model.Repository;
import org.openapitools.client.model.RepositoryCreation;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RepositoriesApi
 */
@Ignore
public class RepositoriesApiTest {

    private final RepositoriesApi api = new RepositoriesApi();

    
    /**
     * create repository
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createRepositoryTest() throws ApiException {
        RepositoryCreation repository = null;
        Repository response = api.createRepository(repository);

        // TODO: test validations
    }
    
    /**
     * delete repository
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteRepositoryTest() throws ApiException {
        String repository = null;
        api.deleteRepository(repository);

        // TODO: test validations
    }
    
    /**
     * get repository
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRepositoryTest() throws ApiException {
        String repository = null;
        Repository response = api.getRepository(repository);

        // TODO: test validations
    }
    
    /**
     * list repositories
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listRepositoriesTest() throws ApiException {
        String after = null;
        Integer amount = null;
        InlineResponse2005 response = api.listRepositories(after, amount);

        // TODO: test validations
    }
    
}
