/*
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.RetentionPolicy;
import org.openapitools.client.model.RetentionPolicyWithCreationDate;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RetentionApi
 */
@Ignore
public class RetentionApiTest {

    private final RetentionApi api = new RetentionApi();

    
    /**
     * 
     *
     * get retention policy for repository
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRetentionPolicyTest() throws ApiException {
        String repository = null;
        RetentionPolicyWithCreationDate response = api.getRetentionPolicy(repository);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * set retention policy for repository
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateRetentionPolicyTest() throws ApiException {
        String repository = null;
        RetentionPolicy policy = null;
        api.updateRetentionPolicy(repository, policy);

        // TODO: test validations
    }
    
}
