/*
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CredentialsWithSecret;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.Setup;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SetupApi
 */
@Ignore
public class SetupApiTest {

    private final SetupApi api = new SetupApi();

    
    /**
     * setup lakeFS and create the first user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setupLakeFSTest() throws ApiException {
        Setup user = null;
        CredentialsWithSecret response = api.setupLakeFS(user);

        // TODO: test validations
    }
    
}
